/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoforca;

import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author yuri.jwsilva
 */
public class JogoDaForca extends javax.swing.JFrame {

    /**
     * Creates new form JogoDaForca
     */
    public JogoDaForca() {
        initComponents();
        
        JButton[] botoes = new JButton[26];
        
        painelTeclado.setLayout(new GridLayout(4, 2, 5, 5));
        for (int i = 0; i < botoes.length; i++) {
            String letra = String.valueOf((char) ('A'+i));
            botoes[i]= new JButton(letra);
            JButton botao = botoes[i];
            botao.setFocusable(false);
            
            botao.addActionListener(e -> pressionaLetra(botao));
            painelTeclado.add(botoes[i]);
        }
        atualizaCampo();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoPalavra = new javax.swing.JTextField();
        painelTeclado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoPalavra.setText("PALAVRA");

        javax.swing.GroupLayout painelTecladoLayout = new javax.swing.GroupLayout(painelTeclado);
        painelTeclado.setLayout(painelTecladoLayout);
        painelTecladoLayout.setHorizontalGroup(
            painelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        painelTecladoLayout.setVerticalGroup(
            painelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(campoPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(painelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        campoPalavra.getAccessibleContext().setAccessibleName("campoPalavra");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pressionaLetra(JButton botao) {                                
        // TODO add your handling code here:
        
        String letra = botao.getText();
        for (int i = 0; i < letrasUtilizadas.length; i++) {
            if(letrasUtilizadas[i] == null || letrasUtilizadas[i].isEmpty()) {
                letrasUtilizadas[i] = letra;
                botao.setEnabled(false);
                if(verificaLetra(letra))
                    atualizaCampo();
                else
                    System.out.println("Errou!");
                break;
            } else if (letrasUtilizadas[i] == letra) {
                System.out.println("Letra utilizada!");
                break;
            }
        }
    } 
    public String[] letrasUtilizadas = new String[26];
    public String palavraInicial = "SAO BATISTA";
    
    private void atualizaCampo () {
        String campo = "";
        for (int i = 0; i < palavraInicial.length(); i++) {
            boolean validado = false;
            for (int j = 0; j < letrasUtilizadas.length; j++) {
                if(letrasUtilizadas[j] != null) {
                    if(palavraInicial.charAt(i) == letrasUtilizadas[j].charAt(0)) {
                        campo += " " + letrasUtilizadas[j].charAt(0) + " ";
                        validado = true;
                        break;
                    }
                }
            }
            if(!validado) {
                if(palavraInicial.charAt(i) == ' ')
                    campo += " - ";
                else 
                    campo += " _ ";
            }
        }
        campoPalavra.setText(campo);
    }
    
    private boolean verificaLetra (String letra) {
        for (int i = 0; i < palavraInicial.length(); i++) {
            if(palavraInicial.charAt(i) == letra.charAt(0))
                return true;
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDaForca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoPalavra;
    private javax.swing.JPanel painelTeclado;
    // End of variables declaration//GEN-END:variables
}
