/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoforca;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author roberto.jwsilva
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    public int tentativa = 1;
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoforca/Nivel0_Forca.png"))); // NOI18N
        jLabel1.setText("nivel0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(236, 236, 236))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        switch (tentativa) {
            case 1:
                ImageIcon imgForca_1 = new ImageIcon(getClass().getResource("/jogoforca/Nivel1_Forca.png"));
                Image ImgCartaImg = imgForca_1.getImage().getScaledInstance(354,481, Image.SCALE_DEFAULT);
                jLabel1.setIcon(new ImageIcon(ImgCartaImg));
                break;
            case 2:
                {
                    ImageIcon imgForca_2 = new ImageIcon(getClass().getResource("/jogoforca/Nivel2_Forca.png"));
                    Image ImgCartaImg1 = imgForca_2.getImage().getScaledInstance(354,481, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(ImgCartaImg1));
                    break;
                }
            case 3:
                {
                    ImageIcon imgForca_2 = new ImageIcon(getClass().getResource("/jogoforca/Nivel3_Forca.png"));
                    Image ImgCartaImg1 = imgForca_2.getImage().getScaledInstance(354,481, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(ImgCartaImg1));
                    break;
                }
                case 4:
                {
                    ImageIcon imgForca_2 = new ImageIcon(getClass().getResource("/jogoforca/Nivel4_Forca.png"));
                    Image ImgCartaImg1 = imgForca_2.getImage().getScaledInstance(354,481, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(ImgCartaImg1));
                    break;
                }
                case 5:
                {
                    ImageIcon imgForca_2 = new ImageIcon(getClass().getResource("/jogoforca/Nivel5_Forca.png"));
                    Image ImgCartaImg1 = imgForca_2.getImage().getScaledInstance(354,481, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(ImgCartaImg1));
                    break;
                }
                case 6:
                {
                    ImageIcon imgForca_2 = new ImageIcon(getClass().getResource("/jogoforca/Nivel6_Forca.png"));
                    Image ImgCartaImg1 = imgForca_2.getImage().getScaledInstance(354,481, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(ImgCartaImg1));
                    break;
                }
            default:
                break;
        }
        tentativa ++;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
